config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :posts do
    resources :measurements
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :measurements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @measurement = @post.measurements.create(measurement_params)
    redirect_to post_path(@post)
  end

private
  def measurement_params
    params.require(:measurement).permit(:F0, :F1)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'new'
    end    
  end


  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

private

  def post_params
    params.require(:post).permit(:line_name, :num_tower, :net_region)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebStgn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Редактрование поста</h1>

<%= form_with model: @post, local: true do |form| %>
  <p>
    <%= form.label :line_name %></br>
    <%= form.text_field :line_name %>
  </p>

  <p>
    <%= form.label :num_tower %></br>
    <%= form.text_field :num_tower %>
  </p>

  <p>
    <%= form.label :net_region %></br>
    <%= form.text_field :net_region %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Все посты', posts_path %>

app/views/posts/index.html.erb
<h1>Установленные посты</h1>

<div>

<% @posts.each do |post| %>
  <div>
    <%= post.line_name %>
    №: <%= post.num_tower %>
    <%= post.net_region %>
    <%= link_to 'Показать', post_path(post) %>
    <%= link_to 'Редактировать', edit_post_path(post) %>
    <%= link_to 'Удалить', 
          post_path(post), 
          method: :delete,
          data: { confirm: 'Уверены?' }  %>
  </div>
<% end %>

</div>

<%= link_to 'Главная', welcome_index_path %> | <%= link_to 'Новый пост', new_post_path %>

app/views/posts/new.html.erb
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <p>
    <%= form.label :line_name %></br>
    <%= form.text_field :line_name %>
  </p>

  <p>
    <%= form.label :num_tower %></br>
    <%= form.text_field :num_tower %>
  </p>

  <p>
    <%= form.label :net_region %></br>
    <%= form.text_field :net_region %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Все посты', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Линия:</strong>
  <%= @post.line_name %>
</p>
<p>
  <strong>Опора:</strong>
  <%= @post.num_tower %>
</p>
<p>
  <strong>Сетевой район:</strong>
  <%= @post.net_region %>
</p>

<h2>Результаты измерений:</h2>
<% @post.measurements.each do |measurement|  %>
  <p>
    <strong>Дата: </strong><%= measurement.created_at%>&nbsp;
    <strong>F0: </strong><%= measurement.F0%> кг,&nbsp;
    <strong>F1: </strong><%= measurement.F1%> кг
  <p>
<% end %>

<h2>Новое измерение:</h2>

<%= form_with model: [@post, @post.measurements.build], local: true do |form|  %>
<p>
  <%= form.label :F0 %></br>
  <%= form.text_field :F0 %>
</p>

<p>
  <%= form.label :F1 %></br>
  <%= form.text_field :F1 %>
</p>
<p>
  <%= form.submit %>
</p>

<% end %>

<%= link_to 'Редактировать', edit_post_path(@post) %> | <%= link_to 'Все посты', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome aboard!</h1>
<%= link_to 'Установленные посты', controller: 'posts' %>